### ISSUE TITLE
Standardize formatting

### ISSUE THREAD

**Issue by ryanknu** [jorgio-castello/ThermHub#2]
Please use consistent formatting across the project. For example, `App.tsx` uses a 2-space indentation and `Header.tsx` uses a 4-space indentation.

Also consider enabling `editor.formatOnSave` in VS Code and then opening and saving every file.

This would make it a lot easier to contribute! Thank you!

**Comment by jorgio-castello** [comment]
Thank you, Ryan! I've made the formatting consistent throughout the project. Let me know if you think I missed anything.

https://github.com/jorgio-castello/ThermHub/commit/7214e74aca4118caf8325db42f0d93b8cdbb5dc0?branch=7214e74aca4118caf8325db42f0d93b8cdbb5dc0&diff=unified
